config/routes.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do
  resources :status_messages, :only   => [:create, :destroy, :show]
  resources :comments,        :except => [:index]
  resources :requests,        :except => [:edit, :update]
  resources :photos,          :except => [:index]
  resources :services

  resources :people
  resources :people do
    resources :status_messages
    resources :photos
  end
  match '/people/by_handle' => 'people#retrieve_remote', :as => 'person_by_handle'

  match '/auth/:provider/callback' => 'services#create'

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :invitations   => "invitations"}
  # added public route to user
  match 'public/:username',          :to => 'users#public'
  match 'getting_started',           :to => 'users#getting_started', :as => 'getting_started'
  match 'users/export',              :to => 'users#export'
  match 'users/export_photos',       :to => 'users#export_photos'
  match 'login',                     :to => 'users#sign_up'
  resources :users,                  :except => [:create, :new, :show]

  match 'aspects/move_contact',  :to => 'aspects#move_contact', :as => 'move_contact'
  match 'aspects/add_to_aspect',:to => 'aspects#add_to_aspect', :as => 'add_to_aspect'
  match 'aspects/remove_from_aspect',:to => 'aspects#remove_from_aspect', :as => 'remove_from_aspect'
  match 'aspects/manage',       :to => 'aspects#manage'
  resources :aspects,           :except => [:edit]

  #match 'warzombie',          :to   => "dev_utilities#warzombie"
  #match 'zombiefriends',      :to   => "dev_utilities#zombiefriends"
  #match 'zombiefriendaccept', :to   => "dev_utilities#zombiefriendaccept"
  #match 'set_backer_number',  :to   => "dev_utilities#set_backer_number"
  #match 'set_profile_photo',  :to   => "dev_utilities#set_profile_photo"

  #public routes
  match 'webfinger',            :to => 'publics#webfinger'
  match 'hcard/users/:id',      :to => 'publics#hcard'
  match '.well-known/host-meta',:to => 'publics#host_meta'
  match 'receive/users/:id',    :to => 'publics#receive'
  match 'hub',                  :to => 'publics#hub'
  #match 'log',                  :to => "dev_utilities#log"


  #root
  root :to => 'home#show'
end

app/models/person.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require File.join(Rails.root, 'lib/hcard')

class Person
  include MongoMapper::Document
  include ROXML
  include Encryptor::Public
  require File.join(Rails.root, 'lib/diaspora/websocket')
  include Diaspora::Socketable

  xml_accessor :_id
  xml_accessor :diaspora_handle
  xml_accessor :url
  xml_accessor :profile, :as => Profile
  xml_reader :exported_key

  key :url, String
  key :diaspora_handle, String, :unique => true
  key :serialized_public_key, String

  key :owner_id, ObjectId

  one :profile, :class_name => 'Profile'
  validates_associated :profile
  delegate :first_name, :last_name, :to => :profile
  before_save :downcase_diaspora_handle 
  
  def downcase_diaspora_handle
    diaspora_handle.downcase!
  end

  belongs_to :owner, :class_name => 'User'

  timestamps!
  
  before_destroy :remove_all_traces
  before_validation :clean_url
  validates_presence_of :url, :profile, :serialized_public_key
  validates_uniqueness_of :diaspora_handle, :case_sensitive => false
  #validates_format_of :url, :with =>
  #  /^(https?):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*(\.[a-z]{2,5})?(:[0-9]{1,5})?(\/.*)?$/ix

  ensure_index :diaspora_handle

  scope :searchable, where('profile.searchable' => true)

  attr_accessible :profile

  def self.search(query)
    return [] if query.to_s.empty?
    query_tokens = query.to_s.strip.split(" ")
    full_query_text = Regexp.escape(query.to_s.strip)

    p = []

    query_tokens.each do |token|
      q = Regexp.escape(token.to_s.strip)
      p = Person.searchable.all('profile.first_name' => /^#{q}/i, 'limit' => 30) \
 | Person.searchable.all('profile.last_name' => /^#{q}/i, 'limit' => 30) \
 | Person.searchable.all('diaspora_handle' => /^#{q}/i, 'limit' => 30) \
 | p
    end
  
    return p
  end

  def real_name
    if profile.first_name.nil? || profile.first_name.empty?
      self.diaspora_handle
    else
      "#{profile.first_name.to_s} #{profile.last_name.to_s}"
    end
  end

  def owns?(post)
    self.id == post.person.id
  end

  def receive_url
    "#{self.url}receive/users/#{self.id}/"
  end

  def public_url
    "#{self.url}public/#{self.owner.username}"
  end


  def public_key_hash
    Base64.encode64 OpenSSL::Digest::SHA256.new(self.exported_key).to_s
  end

  def public_key
    OpenSSL::PKey::RSA.new(serialized_public_key)
  end

  def exported_key
    serialized_public_key
  end

  def exported_key= new_key
    raise "Don't change a key" if serialized_public_key
    @serialized_public_key = new_key
  end

  #database calls
  def self.by_account_identifier(identifier)
    identifier = identifier.strip.downcase.gsub('acct:', '')
    self.first(:diaspora_handle => identifier)
  end

  def self.local_by_account_identifier(identifier)
    person = self.by_account_identifier(identifier)
   (person.nil? || person.remote?) ? nil : person
  end

  def self.build_from_webfinger(profile, hcard)
    return nil if profile.nil? || !profile.valid_diaspora_profile?
    new_person = Person.new
    new_person.exported_key = profile.public_key
    new_person.id = profile.guid
    new_person.diaspora_handle = profile.account
    new_person.url = profile.seed_location

    #hcard_profile = HCard.find profile.hcard.first[:href]
    Rails.logger.info("hcard: #{ hcard.inspect}")
    new_person.url = hcard[:url]
    new_person.profile = Profile.new( :first_name => hcard[:given_name],
                                      :last_name  => hcard[:family_name],
                                      :image_url  => hcard[:photo],
                                      :searchable => hcard[:searchable])

    new_person.save! ? new_person : nil
  end

  def remote?
    owner_id.nil?
  end

  def as_json(opts={})
    {
      :person => {
        :id           => self.id,
        :name         => self.real_name,
        :diaspora_handle => self.diaspora_handle,
        :url          => self.url,
        :exported_key => exported_key
      }
    }
  end
  protected

  def clean_url
    self.url ||= "http://localhost:3000/" if self.class == User
    if self.url
      self.url = 'http://' + self.url unless self.url.match(/https?:\/\//)
      self.url = self.url + '/' if self.url[-1, 1] != '/'
    end
  end

  private
  def remove_all_traces
    Post.all(:person_id => id).each { |p| p.delete }
  end
end

app/controllers/people_controller.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class PeopleController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html
  respond_to :json, :only => [:index, :show]

  def index
    @aspect = :search

    @people = Person.search(params[:q]).paginate :page => params[:page], :per_page => 25, :order => 'created_at DESC'
    
    #only do it if it is an email address
    if params[:q].try(:match, Devise.email_regexp)
      webfinger(params[:q])
    end
    
    if @people.count == 1
      redirect_to @people.first
    else
      respond_with @people
    end
  end

  def show
    @person = Person.find(params[:id].to_id)
    @post_type = :all
    @aspect = :none 
    if @person
      @profile = @person.profile
      @contact = current_user.contact_for(@person)
      @is_contact = @person != current_user.person && @contact

      if @contact
        @aspects_with_person = @contact.aspects
      end

      @posts = current_user.visible_posts(:person_id => @person.id, :_type => "StatusMessage").paginate :page => params[:page], :order => 'created_at DESC'
      respond_with @person, :locals => {:post_type => :all}

    else
      flash[:error] = I18n.t 'people.show.does_not_exist'
      redirect_to people_path
    end
  end

  def destroy
    current_user.disconnect(current_user.visible_person_by_id(params[:id]))
    respond_with :location => root_url
  end

  def edit
    @aspect  = :person_edit
    @person  = current_user.person
    @profile = @person.profile
  end

  def update
    # convert date selector into proper timestamp
    
    if birthday = params[:date]
      unless [:month, :day, :year].any?{|x| birthday[x].blank?} 
        params[:person][:profile][:birthday] ||= Date.parse("#{birthday[:year]}-#{birthday[:month]}-#{birthday[:day]}")
      end
    end

    # upload and set new profile photo
    params[:person][:profile] ||= {}
    if params[:person][:profile][:image].present?
      raw_image = params[:person][:profile].delete(:image)
      params[:profile_image_hash] = { :user_file => raw_image, :to => "all" }

      photo = current_user.post(:photo, params[:profile_image_hash])
      params[:person][:profile][:image_url] = photo.url(:thumb_large)
    end

    if current_user.update_profile params[:person][:profile]
      flash[:notice] = I18n.t 'people.update.updated'
    else
      flash[:error] = I18n.t 'people.update.failed'
    end

    if params[:getting_started]
      redirect_to getting_started_path(:step => params[:getting_started].to_i+1)
    else
      redirect_to edit_person_path
    end
  end

  def retrieve_remote
    if params[:diaspora_handle]
      webfinger(params[:diaspora_handle], :single_aspect_form => true)
      render :nothing => true
    else
      render :nothing => true, :status => 422
    end
  end

  private
  def webfinger(account, opts = {})
    finger = EMWebfinger.new(account)
    finger.on_person do |response|
      if response.class == Person
        response.socket_to_uid(current_user.id, opts)
      else
        require File.join(Rails.root,'lib/diaspora/websocket')
        Diaspora::WebSocket.queue_to_user(current_user.id, {:class => 'people', :status => 'fail', :query => account, :response => response}.to_json)
      end
    end
  end
end

app/helpers/people_helper.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module PeopleHelper

  def request_partial single_aspect_form
    if single_aspect_form
      'requests/new_request_with_aspect_to_person'
    else
      'requests/new_request_to_person'
    end
  end

  def search_or_index
    if params[:q]
      I18n.t 'people.helper.results_for',:params => params[:q]
    else
      I18n.t "people.helper.people_on_pod_are_aware_of"
    end
  end

  def action_link(person, is_contact)
    if is_contact
      link_to t('people.profile_sidebar.remove_contact'), person, :confirm => t('are_you_sure'), :method => :delete
    elsif person == current_user.person
      link_to t('people.profile_sidebar.edit_my_profile'), edit_person_path(person)
    end
  end

  def pending_request_for(person)
    current_user.request_for(person)
  end

end

app/views/people/_person.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%li.message{:id => person.id}

  = person_image_link(person)

  .content
    %span.from
      = link_to person.real_name, person_path(person)

      .right{:style=>"display:inline;"}
        - if person.id == current_user.person.id
          = t('.thats_you')
        - elsif current_user.person_objects.include?(person)
          = t('.already_connected')
        - elsif current_user.request_for(person)
          = link_to t('.pending_request'), aspects_manage_path
        - else
          - single_aspect_form ||= nil
          = render(:partial => request_partial(single_aspect_form), :locals => {:aspects => aspects, :destination_handle => person.diaspora_handle})

    .info
      = person.diaspora_handle

app/views/people/_profile_photo_upload.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


#profile_photo_upload
  = owner_image_tag
  = form.file_field :image

  -if !@aspect.nil? && @aspect != :getting_started 
    %p
      \...#{t('.or_select_one')}
      = link_to t('_photos'), person_photos_path(@person)

app/views/people/_profile_sidebar.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

#profile
  .profile_photo
    = person_image_link(person, :to => :photos)

  = action_link(person, is_contact)

  %ul
    - if @posts.first
      %li
        %i= t(".last_seen",:how_long_ago => how_long_ago(@posts.first))

    - if is_contact
      %li
        %ul#aspects_for_person
          %b in aspects
          %br
          - for aspect in @aspects_with_person
            %li= link_to aspect.name, aspect

  -if is_contact || person == current_user.person
    %ul#profile_information
      %li  
        %b #{t('.bio')}
        %br
        = person.profile.bio
      %li
        %b #{t('.gender')}
        %br
        = person.profile.gender
      %li
        %b #{t('.born')}
        %br
        = "#{time_ago_in_words(person.profile.birthday)} #{t('ago')}" if @person.profile.birthday

  %b.small= person.diaspora_handle

app/views/people/_profile_sidebar.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  :javascript
    $(document).ready(function(){
      $('.delete').bind('ajax:success', function() {
        $(this).closest('li').fadeOut(200);
      });
      $('.delete').bind('ajax:failure', function() {
        alert("#{t('.cannot_remove', :name => person.real_name)}");
      });
    });


#profile
  .profile_photo
    = person_image_link(person, :to => :photos)

  = action_link(person, is_contact)

  %ul
    - if is_contact
      %li
        %ul#aspects_for_person
          %b= t('.in_aspects')
          %br
          - for aspect in @aspects_with_person
            %li
              = link_to aspect.name, aspect
              = link_to "x", {:controller => "aspects", :action => "remove_from_aspect", :person_id => person.id, :aspect_id => aspect.id}, :confirm => t('.remove_from', :name => person.real_name, :aspect => aspect), :remote => true, :class => "delete"
              

  -if is_contact || person == current_user.person
    %ul#profile_information
      %li  
        %h3 #{t('.bio')}
        = person.profile.bio

      %li
        .span-4
          %h3 #{t('.gender')}
          = person.profile.gender

        .span-4.last
          %h3 #{t('.born')}
          = "#{time_ago_in_words(person.profile.birthday)} #{t('ago')}" if @person.profile.birthday

app/views/people/edit.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


#section_header
  %h2
    = t('settings')
  %ul#settings_nav
    %li=link_to t('profile'), edit_person_path(current_user.person)
    %li=link_to t('account'), edit_user_path(current_user)
    %li=link_to t('_services'), services_path

.span-19.prepend-5.last
  = form_for @person, :html => { :multipart => true } do |person|
    %h3
      = t('.your_profile')
      .description
        =t('.info_available_to')

    = person.error_messages

    = person.fields_for :profile do |profile|
      %h4
        = t('.your_name')
        = profile.text_field :first_name, :value => @profile.first_name, :placeholder => t('.first_name')
        = profile.text_field :last_name, :value => @profile.last_name, :placeholder => t('.last_name')

      %h4
        = t('.your_gender')
        %br
        = profile.text_field :gender, :value => @profile.gender, :placeholder => t('fill_me_out')

      %h4
        = t('.your_birthday')
        %br
        = select_date @person.profile.birthday, :prompt => true, :default => true, :order => t('date.order'), :start_year => 2000, :end_year => 1930

      %h4
        = t('.your_bio')
        = profile.text_area :bio, :value => @profile.bio, :rows => 5, :placeholder => t('fill_me_out')

      %h4
        = t('.your_photo')
        = render 'people/profile_photo_upload', :form => profile

      %h4
        = t('search')
        %p{:class=>"checkbox_select"}
          = profile.label :searchable, t('.allow_search')
          = profile.check_box :searchable, {:checked => @person.profile.searchable}, true, false

    .submit_block
      = link_to t('cancel'), edit_user_path(current_user)
      = t('or')
      = person.submit t('.update_profile')

app/views/people/index.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.span-15.prepend-5.last
  %h2
    =t('.results_for')
    %u= params[:q]

  %ul{:class => 'stream people', :id => 'people_stream'}
    - for person in @people
      = render 'people/person', :person => person, :aspects => @aspects

  = will_paginate @people

app/views/people/show.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


.span-24.last
  #author_info
    .from{:style=>"padding-left:0;display:block;"}
      %h2{:style=>"display:block;"}
        = @person.real_name
        .right{:style => "top:0;"}
          %span.description
            = @person.diaspora_handle

      #person_nav_links
        = link_to t('layouts.header.view_profile'), person_path(@person)
        = link_to t('_photos'), person_photos_path(@person)

.span-8.append-1.last
  = render :partial => 'people/profile_sidebar', :locals => {:person => @person, :is_contact => @is_contact}

.span-15.last
  - if @contact || current_user.person == @person

    - if @posts.count > 0
      -if @post_type == :photos
        = render 'photos/index', :photos => @posts
      - else
        = render 'shared/stream', :posts => @posts
      = will_paginate @posts

    - else
      %ul#stream
        %li
          %h3= t('.no_posts')

  - elsif current_user.has_incoming_request_from(@person)
    .floating
      %h3 
        = t('.incoming_request') 
      %h4
        = link_to t('.return_to_aspects'), aspects_manage_path
        = t('.to_accept_or_ignore')
        
  - else
    .floating
      %h3
        = t('.not_connected', :name => @person.real_name)
        
      - unless pending_request_for(@person)
        %h3
          .description
            = t('.request_people')
         
        = render :partial =>'requests/new_request_to_person', :locals => {:aspects => @aspects, :destination_handle => @person.diaspora_handle}

      - else
        %h3
          .description
            = t('.already_requested', :name => @person.real_name)

app/views/people/show.mobile.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


- content_for :page_title do
  profile

- content_for :left_pane do
  #profile
    .profile_photo
      = person_image_link(@person)
    %ul
      -unless @posts.first.nil?
        %li
          %i= t(".last_seen",:how_long_ago => how_long_ago(@posts.first))
      - if @person != current_user.person && current_user.friends.include?(@person)
        %li
          %i= t(".friends_since",:how_long_ago => how_long_ago(@person))
        %li
          = form_tag move_friend_path
          = select :to, :to,  @aspects_dropdown_array, :selected => @aspects_with_person.first.id
          = hidden_field_tag :from, :from, :value => @aspects_with_person.first.id
          = hidden_field_tag :friend_id, :friend_id, :value => @person.id
          = submit_tag t('.save')

    - if @person != current_user.person && current_user.friends.include?(@person)
      = link_to t('.remove_friend'), @person, :confirm => t('.are_you_sure'), :method => :delete, :class => "button"


- if @posts
  %ul#stream
    - for post in @posts
      = render type_partial(post), :post => post unless post.class == Album
    = will_paginate @posts
- else
  %h3=t('no posts to display!')